#!/bin/bash
# rebrand-upstream.sh - deterministically transform a pristine tw93/Mole tree
# into the Pear tree (github.com/RawSalmon69/pear-cli).
#
# Usage: scripts/rebrand-upstream.sh <upstream-tree-dir>
#
# The rebrand is a fixed, ordered list of transforms. Structural transforms are
# anchor-asserted: if an expected anchor is missing, the script prints which
# transform failed and exits 1. That failure is the signal that upstream
# refactored something and the transform needs a human look.
#
# Protected paths are never generated by this script; the sync workflow copies
# them from our main branch instead:
#   README.md, docs/superpowers/**, companion/**, scripts/rebrand-upstream.sh,
#   scripts/UPSTREAM_BASE, .github/workflows/sync-upstream.yml,
#   .github/workflows/companion.yml, .github/workflows/companion-release.yml
set -euo pipefail

TREE="${1:?usage: rebrand-upstream.sh <upstream-tree-dir>}"
cd "$TREE"

fail() {
    echo "REBRAND FAILED: $*" >&2
    exit 1
}

# Sanity: input must be a pristine upstream Mole tree, not the Pear repo.
[[ -f mole && -f mo ]] || fail "sanity: $TREE does not look like a Mole tree (missing ./mole or ./mo)"
[[ -e scripts/rebrand-upstream.sh || -e pear ]] && fail "sanity: $TREE looks like the Pear repo, refusing to run"

# resub LABEL FILE PERL_REGEX REPLACEMENT [MIN]
#   Whole-file (slurped) regex substitution. Fails unless >= MIN replacements.
resub() {
    local label="$1" file="$2" re="$3" rep="$4" min="${5:-1}"
    [[ -f "$file" ]] || fail "$label: file not found: $file"
    RB_RE="$re" RB_REP="$rep" RB_MIN="$min" perl -0777 -pi -e \
        '$n += (s/$ENV{RB_RE}/$ENV{RB_REP}/g || 0); END { exit 1 if ($n // 0) < $ENV{RB_MIN} }' \
        "$file" || fail "$label: anchor not found in $file (expected >= $min match(es) of: $re)"
}

# litsub LABEL FILE LITERAL REPLACEMENT [MIN]
#   Same as resub but LITERAL is matched verbatim (regex-quoted).
litsub() {
    local label="$1" file="$2" lit="$3" rep="$4" min="${5:-1}"
    [[ -f "$file" ]] || fail "$label: file not found: $file"
    RB_RE="$lit" RB_REP="$rep" RB_MIN="$min" perl -0777 -pi -e \
        '$n += (s/\Q$ENV{RB_RE}\E/$ENV{RB_REP}/g || 0); END { exit 1 if ($n // 0) < $ENV{RB_MIN} }' \
        "$file" || fail "$label: anchor not found in $file (expected >= $min literal match(es))"
}

# optsub LABEL FILE PERL_REGEX REPLACEMENT
#   Optional substitution: applied when present, no failure when absent.
#   Used only for upstream text that legitimately comes and goes (Mole Mac app
#   references that upstream itself adds/removes between releases).
optsub() {
    local label="$1" file="$2" re="$3" rep="$4"
    [[ -f "$file" ]] || fail "$label: file not found: $file"
    RB_RE="$re" RB_REP="$rep" perl -0777 -pi -e 's/$ENV{RB_RE}/$ENV{RB_REP}/g' "$file" \
        || fail "$label: perl error on $file"
}

del_file() {
    local label="$1" file="$2"
    [[ -e "$file" ]] || fail "$label: expected upstream file missing: $file"
    rm -f "$file"
}

ren_file() {
    local label="$1" from="$2" to="$3"
    [[ -e "$from" ]] || fail "$label: missing $from"
    [[ -e "$to" ]] && fail "$label: $to already exists"
    mv "$from" "$to"
}

# ---------------------------------------------------------------------------
# Phase 1 - deletions (rule 6 + protected README.md, regenerated from ours)
# ---------------------------------------------------------------------------
del_file del-trademark        TRADEMARK.md
del_file del-contributors-svg CONTRIBUTORS.svg
del_file del-funding          .github/FUNDING.yml
del_file del-macapp-bug       .github/ISSUE_TEMPLATE/mac_app_bug.yml
del_file del-macapp-feature   .github/ISSUE_TEMPLATE/mac_app_feature.yml
del_file del-update-contrib   .github/workflows/update-contributors.yml
del_file del-readme-protected README.md

# ---------------------------------------------------------------------------
# Phase 2 - special content edits (run before generic renames; anchors are
# upstream text)
# ---------------------------------------------------------------------------

# 2.1 AGENTS.md: drop/reword Mole Mac app product references (rule 8)
litsub agents-mac-crosslink AGENTS.md \
    '- Keep Mole Mac references as a cross-link or support path. The CLI and Mac app can share product values without requiring feature parity.
' ''
litsub agents-gui-parity AGENTS.md \
    '- Do not treat Mole Mac features as required CLI gaps. The CLI should stay narrower, scriptable, and safety-first when parity would add complexity or ambiguity.' \
    '- Do not add features just to mirror a GUI app. The CLI should stay narrow, scriptable, and safety-first when extra surface would add complexity or ambiguity.'
litsub agents-mac-ui AGENTS.md \
    'Would this be better as Mole Mac UI, documentation, a warning, or an explicit "not supported" answer?' \
    'Would this be better as documentation, a warning, or an explicit "not supported" answer?'
litsub agents-mac-issues AGENTS.md \
    '- Keep CLI issues and Mole Mac app issues separate. A fix in `mole-mac` does not imply a close in this CLI repo, and a CLI fix does not prove a Mac app issue is fixed unless the Mac app release path is verified.
' ''
# Mole-Mac remote diagnostics + maintainer closeout bullets: upstream added
# these after our base; they are Mac-app support flows, replaced by the plain
# CLI guidance line they superseded. Optional because older upstream snapshots
# do not contain them.
optsub agents-mac-diagnostics AGENTS.md \
    '- \*\*Remote diagnostics for unreproducible reports\*\*:[^\n]*\n- \*\*Default issue closeout pipeline\*\*[^\n]*\n' \
    '- If a fix is on `main` but not in a stable release, prefer telling CLI users to try `mo update --nightly` now, then mention the next stable release only when that path is confirmed.
'

# 2.2 cmd/status/view.go: mascot identifiers become cat*, not pear* (rule 5)
resub view-molebody      cmd/status/view.go 'moleBody'     'catBody'     4
resub view-getmoleframe  cmd/status/view.go 'getMoleFrame' 'getCatFrame' 3
resub view-molewidth     cmd/status/view.go 'moleWidth'    'catWidth'    2
litsub view-comment-body   cmd/status/view.go 'Mole body frames (facing right).'  'Cat body frames (facing right).'
litsub view-comment-mirror cmd/status/view.go 'Mirror mole body frames (facing left).' 'Mirror cat body frames (facing left).'
litsub view-comment-render cmd/status/view.go 'renders the animated mole.' 'renders the animated cat.'

# 2.3 cmd/status/view_test.go: mascot test names + frame wording
litsub viewtest-once   cmd/status/view_test.go 'TestRenderHeaderErrorReturnsMoleOnce'  'TestRenderHeaderErrorReturnsCatOnce'
litsub viewtest-single cmd/status/view_test.go 'TestModelViewErrorRendersSingleMole'   'TestModelViewErrorRendersSingleCat'
litsub viewtest-frame  cmd/status/view_test.go 'one mole frame' 'one cat frame' 2

# 2.4 cmd/status/metrics_battery.go: comment no longer references the Mac app
litsub battery-comment cmd/status/metrics_battery.go \
    '// batteryHealthPercent mirrors the algorithm used by the Mole Mac app
// (SystemMetricsCollector.batteryHealthPercent): NominalChargeCapacity is' \
    '// batteryHealthPercent computes battery health the same way macOS reports it:
// NominalChargeCapacity is'

# 2.5 mole script: custom pear banner (rule 8)
read -r -d '' OLD_BANNER << 'RB_EOF' || true
${GREEN} __  __       _      ${NC}
${GREEN}|  \/  | ___ | | ___ ${NC}
${GREEN}| |\/| |/ _ \| |/ _ \\${NC}
${GREEN}| |  | | (_) | |  __/${NC}  ${BLUE}https://mole.fit${NC}
${GREEN}|_|  |_|\___/|_|\___|${NC}  ${GREEN}${MOLE_TAGLINE}${NC}
RB_EOF
read -r -d '' NEW_BANNER << 'RB_EOF' || true
${GREEN}      _       _____                    ${NC}
${GREEN}     (/      |  __ \\                  ${NC}
${GREEN}    (  )     | |__) |__  __ _ _ __     ${NC}
${GREEN}   /    \\    |  ___/ _ \\/ _\` | '__|    ${NC}${BLUE}https://github.com/RawSalmon69/pear-cli${NC}
${GREEN}  ( ^ u ^ )  | |  |  __/ (_| | |       ${NC}${GREEN}${PEAR_TAGLINE}${NC}
${GREEN}   \\.___./   |_|   \\___|\\__,_|_|       ${NC}
RB_EOF
litsub cli-banner mole "$OLD_BANNER" "$NEW_BANNER"

# 2.6 mole script: help text promotes the full `pear` command over the alias
#     (rule 8). Applies to the %-28s help printf lines and display= lines.
perl -pi -e '
    if (/%-28s/) { $n1 += (s/"mo"/"pear"/g || 0); $n2 += (s/"mo /"pear /g || 0); }
    $n3 += (s/display="mo /display="pear /g || 0);
    END { exit 1 unless ($n1 // 0) >= 1 && ($n2 // 0) >= 10 && ($n3 // 0) >= 3 }
' mole || fail "cli-help-promotion: help-text anchors not found in ./mole"

# 2.7 release.yml: drop the Homebrew publish job(s); keep build/release jobs
resub release-drop-homebrew-jobs .github/workflows/release.yml \
    '(?s)\n\n  (?:update-formula|update-personal-tap):\n.*$' $'\n'

# 2.8 tests/scripts.bats: drop the release-workflow Homebrew Core PR test
resub scriptsbats-drop-1209 tests/scripts.bats \
    '(?s)\@test "release workflow keeps the Homebrew Core PR open \(#1209\)" \{\n.*?\n\}\n\n' ''

# 2.9 issue template config: drop the Telegram community link
litsub config-drop-telegram .github/ISSUE_TEMPLATE/config.yml \
    '  - name: Telegram Community
    url: https://t.me/+9f9gf4ZrFSQ2OWVl
    about: Join our Telegram group for questions and discussions
' ''

# 2.10 install.sh: attestation owner (rule 7)
litsub install-owner install.sh '--owner tw93 ' '--owner RawSalmon69 '

# 2.11 quick launchers: Alfred bundle id prefix (rule 7)
litsub launchers-bundle-id scripts/setup-quick-launchers.sh 'fun.tw93.' 'fun.rawsalmon69.'

# 2.12 docs/release-notes/V1.42.0.md: drop Mac-app references kept by upstream
litsub v142-img docs/release-notes/V1.42.0.md \
    '  <img src="https://cdn.tw93.fun/pic/cole.png" alt="Mole Logo" width="120" height="120" style="border-radius:50%" />
' ''
litsub v142-status-en docs/release-notes/V1.42.0.md \
    ', and `mo status` now matches the Mac App health signals more closely' ''
litsub v142-status-cn docs/release-notes/V1.42.0.md \
    '，`mo status` 也更接近 Mac App 的健康状态判断' ''
litsub v142-macapp-section docs/release-notes/V1.42.0.md \
    '### Mole Mac App

Prefer a GUI? Try [Mole Mac App](https://mole.fit), the CLI stays free and open source

' ''
litsub v142-trailing-link docs/release-notes/V1.42.0.md \
    '
> https://github.com/tw93/Mole
' ''

# 2.13 help-output assertions follow the `pear` promotion (rule 8)
resub clibats-help-pear tests/cli.bats '\*"mo ' '*"pear ' 6
resub purgebats-help-pear tests/purge.bats '\*"mo ' '*"pear ' 1

# 2.14 repo-owner references (tw93 the ACCOUNT, as opposed to tw93 appearing
# in path fixtures, the sponsors helper, or the com.tw93.MiaoYan bundle id,
# which all stay)
litsub codeowners-owner .github/CODEOWNERS '* @tw93' '* @RawSalmon69'
resub dependabot-owner .github/dependabot.yml '"tw93"' '"RawSalmon69"' 2
litsub disktest-home cmd/status/metrics_disk_test.go \
    '/Users/tw93/Library/Caches/dev.kaku' '/Users/RawSalmon69/Library/Caches/dev.kaku'

# ---------------------------------------------------------------------------
# Phase 3 - generic brand passes over every text file (rules 1-3, 7)
# ---------------------------------------------------------------------------
TEXT_LIST=$(mktemp)
trap 'rm -f "$TEXT_LIST"' EXIT
# -type f skips symlinks (CLAUDE.md -> AGENTS.md must stay a symlink);
# grep -Il skips binary files.
find . -type f ! -path './.git/*' -exec grep -Il '' {} + > "$TEXT_LIST" || true
[[ -s "$TEXT_LIST" ]] || fail "generic: no text files found under $TREE"

xargs perl -0777 -pi -e '
    s{tw93/\(\?:Mole\|mole\)}{RawSalmon69/pear-cli}g;
    s{tw93/[Mm]ole}{RawSalmon69/pear-cli}g;
    s{tw93/homebrew-tap}{RawSalmon69/homebrew-tap}g;
    s{https://mole\.fit}{https://github.com/RawSalmon69/pear-cli}g;
    s{hitw93\@gmail\.com}{worached.ink\@dappmaker.co.th}g;
    s/MOLE_/PEAR_/g;
    s/\bMO_/PE_/g;
    s/MOLE/PEAR/g;
    s/Mole/Pear/g;
    s/mole/pear/g;
    s/\bmo_/pe_/g;
    s/\xF0\x9F\x90\xB9/\xF0\x9F\x8D\x90/g; # hamster mascot -> pear
' < "$TEXT_LIST" || fail "generic: brand pass failed"

# Standalone CLI alias word mo -> pe. Not applied to Go sources (their
# comments keep `mo <cmd>` wording upstream-style) and never to the
# "N months" age label in lib/clean/project.sh ("$((_age_d / 30))mo").
grep -v '\.go$' "$TEXT_LIST" | xargs perl -0777 -pi -e \
    's/(?<!\)\))\bmo\b/pe/g' || fail "generic: standalone-mo pass failed"

# ---------------------------------------------------------------------------
# Phase 4 - file renames (rule 4)
# ---------------------------------------------------------------------------
ren_file rename-cli         mole pear
ren_file rename-alias       mo   pe
ren_file rename-fileops-test tests/file_ops_mole_delete.bats tests/file_ops_pear_delete.bats
ren_file rename-cursor-rule .cursor/rules/mole-test-safety.mdc .cursor/rules/pear-test-safety.mdc

# ---------------------------------------------------------------------------
# Phase 5 - post-checks (canaries: fail loudly when upstream introduces brand
# tokens somewhere the transforms above do not cover)
# ---------------------------------------------------------------------------
if find . -path ./.git -prune -o -print | grep -i 'mole' > /dev/null; then
    find . -path ./.git -prune -o -print | grep -i 'mole' >&2
    fail "post-check: residual 'mole' in a path"
fi
if grep -rIl --exclude-dir=.git -i 'mole' . > /dev/null 2>&1; then
    grep -rIn --exclude-dir=.git -i 'mole' . >&2 | head -20 || true
    fail "post-check: residual 'mole' token in file contents"
fi
# tw93 may remain only as: CDN image host, the MiaoYan bundle id, an example
# username in protected-path fixtures, the sponsors helper, and the
# release-notes contributor-exclusion rule.
RESIDUAL_TW93=$(grep -rIn --exclude-dir=.git 'tw93' . \
    | grep -v 'cdn\.tw93\.fun' \
    | grep -v 'com\.tw93\.MiaoYan' \
    | grep -v '/Users/tw93' \
    | grep -v '^\./\.claude/skills/release-notes/scripts/sponsors\.sh:' \
    | grep -v 'Exclude `tw93` and bots' || true)
if [[ -n "$RESIDUAL_TW93" ]]; then
    echo "$RESIDUAL_TW93" >&2
    fail "post-check: residual 'tw93' reference outside the allowed exceptions"
fi
if grep -rIn --exclude-dir=.git 'hitw93' . > /dev/null 2>&1; then
    fail "post-check: residual upstream email"
fi
if grep -rIn --exclude-dir=.git '🐹' . > /dev/null 2>&1; then
    fail "post-check: residual hamster mascot emoji"
fi
# Standalone `mo` may remain only in Go sources and the project.sh month label.
RESIDUAL_MO=$(grep -v '\.go$' "$TEXT_LIST" | xargs perl -ne \
    'print "$ARGV:$.: $_" if /(?<!\)\))\bmo\b/; close ARGV if eof' 2>/dev/null || true)
if [[ -n "$RESIDUAL_MO" ]]; then
    echo "$RESIDUAL_MO" >&2
    fail "post-check: residual standalone 'mo' outside Go sources"
fi

echo "rebrand OK: $TREE"
