import AppKit
import ApplicationServices

// MARK: - What was selected

/// What the focused element of the frontmost app has selected right now.
struct FocusedSelection: Equatable {
    /// The selected text, or nil when the element reports none — and always nil
    /// for a secure field, whose selection is never read in the first place.
    let text: String?
    /// The focused element is a password field.
    let isSecure: Bool
    /// The process the focused element belongs to.
    let pid: pid_t
}

// MARK: - Where it goes

/// The pasteboard an auto-copy writes to. A protocol so the decision logic can
/// be driven in full without touching the developer's real clipboard.
@MainActor
protocol SelectionPasteboard: AnyObject {
    /// The text already on the pasteboard, so an unchanged selection can be
    /// skipped instead of rewritten.
    var currentText: String? { get }
    func write(_ text: String)
}

/// Pasteboard facts shared by the writer and the test that proves the clipboard
/// history ignores what it writes.
enum HighlightCopy {
    /// nspasteboard.org's marker for content the user did not explicitly copy.
    /// `ClipboardHistoryService.mayRecord` refuses it, and so does every other
    /// manager that honours the convention (Maccy, Paste, …). That is the whole
    /// point: the text pastes with ⌘V like any other copy, but a day of real
    /// copies never gets buried under every stray highlight.
    static let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

    /// Everything one auto-copy puts on the pasteboard: the text, plus the
    /// marker. One list, so the write and the test asserting the history skips
    /// it cannot drift apart. By convention the marker's *value* is irrelevant —
    /// its presence is the entire signal.
    static func payload(for text: String) -> [(type: NSPasteboard.PasteboardType, value: String)] {
        [(.string, text), (autoGeneratedType, "")]
    }

    /// Longest snippet the confirmation toast shows before eliding. The toast
    /// sizes itself to its text, so an un-elided paragraph would be a panel the
    /// width of the display.
    static let snippetLimit = 48

    /// One line of the copied text, for the toast: newlines and runs of
    /// whitespace collapse to single spaces so a multi-line selection still
    /// reads as one line, and anything past `snippetLimit` is elided.
    static func snippet(for text: String) -> String {
        let flat = text.split(whereSeparator: \.isWhitespace).joined(separator: " ")
        guard flat.count > snippetLimit else { return flat }
        return flat.prefix(snippetLimit).trimmingCharacters(in: .whitespaces) + "…"
    }
}

/// The real pasteboard, plus the only thing that says the copy happened.
///
/// The toast lives here rather than in the engine because this is the seam that
/// already separates "a real write" from "a test write": the fake pasteboard the
/// decision tests inject shows nothing, and there is no second flag to keep in
/// step. Silence was the whole complaint — a highlight that lands on the
/// clipboard and a highlight the engine refused look identical without it.
@MainActor
final class SystemSelectionPasteboard: SelectionPasteboard {
    var currentText: String? { NSPasteboard.general.string(forType: .string) }

    func write(_ text: String) {
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        for item in HighlightCopy.payload(for: text) {
            pasteboard.setString(item.value, forType: item.type)
        }
        CopyToast.show(text: HighlightCopy.snippet(for: text))
    }
}

// MARK: - Reading the selection

/// Reads the frontmost app's current text selection through Accessibility.
///
/// Deliberately *not* a synthesised ⌘C. That fires the target app's own copy
/// binding, clobbers the pasteboard even when nothing is selected, and races
/// with anything else reading it. An app whose selection Accessibility cannot
/// read simply does not get this feature — the correct outcome, not a reason to
/// fake a keypress.
enum AXSelectionReader {
    /// Nil when nothing is focused, when the element will not say what it is, or
    /// when Accessibility is not granted (every read fails, so an ungranted app
    /// is inert rather than broken).
    static func read() -> FocusedSelection? {
        let system = AXUIElementCreateSystemWide()
        AXRead.capTimeout(system)
        guard let focused = AXRead.element(system, kAXFocusedUIElementAttribute) else { return nil }
        AXRead.capTimeout(focused)

        var pid: pid_t = 0
        guard AXUIElementGetPid(focused, &pid) == .success else { return nil }

        // A healthy element always answers its role. One that will not is either
        // gone or wedged, and guessing what it is next to a password field is not
        // a trade worth making — bail.
        guard let role = AXRead.string(focused, kAXRoleAttribute) else { return nil }
        guard !isSecure(role: role, subrole: AXRead.string(focused, kAXSubroleAttribute)) else {
            return FocusedSelection(text: nil, isSecure: true, pid: pid)
        }
        return FocusedSelection(
            text: AXRead.string(focused, kAXSelectedTextAttribute), isSecure: false, pid: pid)
    }

    /// Whether the focused element is a password field. Both spellings are real:
    /// a Carbon-era or web secure field reports `AXSecureTextField` as its
    /// **role**, while AppKit's `NSSecureTextField` reports role `AXTextField`
    /// with `AXSecureTextField` as its **subrole**. Checking only one of the two
    /// leaks passwords from half the apps on the machine.
    ///
    /// One string covers both: the SDK spells it once, as
    /// `kAXSecureTextFieldSubrole` in `AXRoleConstants.h`, and there is no
    /// separate role constant to compare against.
    static func isSecure(role: String, subrole: String?) -> Bool {
        role == kAXSecureTextFieldSubrole || subrole == kAXSecureTextFieldSubrole
    }
}

// MARK: - The decision

/// Turns mouse-ups into clipboard writes: X11's primary selection, on macOS.
///
/// Every seam is injected, so when to look, what to refuse and what to write are
/// all testable without reading a real selection or touching a real pasteboard.
@MainActor
final class HighlightCopyEngine {
    /// How far the pointer must travel between down and up before the gesture
    /// counts as a drag rather than a click made with a shaky hand.
    static let dragThreshold: CGFloat = 3

    private let readSelection: () -> FocusedSelection?
    private let pasteboard: any SelectionPasteboard
    private let ownPID: pid_t
    private var downPoint: CGPoint?

    init(
        readSelection: @escaping () -> FocusedSelection? = AXSelectionReader.read,
        pasteboard: any SelectionPasteboard = SystemSelectionPasteboard(),
        ownPID: pid_t = ProcessInfo.processInfo.processIdentifier
    ) {
        self.readSelection = readSelection
        self.pasteboard = pasteboard
        self.ownPID = ownPID
    }

    func mouseDown(at point: CGPoint) {
        downPoint = point
    }

    /// The only place a selection is ever read.
    ///
    /// `.leftMouseUp` fires on every click on the machine and each read is a
    /// synchronous round-trip into another process, so the read is gated on the
    /// mouse-up having actually ended a selection gesture: the pointer moved, or
    /// this is the second click of a double-click (word) or a triple (line). A
    /// plain single click returns here having cost zero Accessibility calls.
    func mouseUp(at point: CGPoint, clickCount: Int) {
        let start = downPoint
        downPoint = nil
        let dragged = start.map {
            hypot(point.x - $0.x, point.y - $0.y) >= Self.dragThreshold
        } ?? false
        guard dragged || clickCount >= 2 else { return }
        guard let text = Self.textToCopy(
            readSelection(), ownPID: ownPID, current: pasteboard.currentText)
        else { return }
        pasteboard.write(text)
    }

    /// Pure policy: the text this selection should put on the pasteboard, or nil
    /// to leave the pasteboard exactly as it is.
    static func textToCopy(
        _ selection: FocusedSelection?, ownPID: pid_t, current: String?
    ) -> String? {
        guard let selection else { return nil }
        // A password must never reach the pasteboard. First check, no exceptions:
        // this is the one bug in this feature that is a security problem rather
        // than an annoyance.
        guard !selection.isSecure else { return nil }
        // Pear's own windows, skipped by pid the way `AXWindowMover.resolveTarget`
        // does — selecting text inside the app is not a highlight-to-copy gesture.
        guard selection.pid != ownPID else { return nil }
        // Clearing a selection must not wipe what the user actually copied.
        guard let text = selection.text,
            !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
        else { return nil }
        // Re-highlighting the same words is not a new copy: writing anyway would
        // bump the pasteboard's changeCount and wake every clipboard watcher.
        guard text != current else { return nil }
        return text
    }
}
